// <auto-generated />
using System;
using GameEngine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameEngine.Migrations
{
    [DbContext(typeof(LudoContext))]
    partial class LudoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GameEngine.Models.DbPlayer", b =>
                {
                    b.Property<int>("DbPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SaveDataId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("DbPlayerId");

                    b.HasIndex("SaveDataId");

                    b.ToTable("DbPlayer");
                });

            modelBuilder.Entity("GameEngine.Models.SaveData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Boardsize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Save");
                });

            modelBuilder.Entity("GameEngine.Models.Turn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PieceID")
                        .HasColumnType("int");

                    b.Property<int?>("Roll")
                        .HasColumnType("int");

                    b.Property<int?>("SaveDataId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SaveDataId");

                    b.ToTable("Turn");
                });

            modelBuilder.Entity("GameEngine.Models.DbPlayer", b =>
                {
                    b.HasOne("GameEngine.Models.SaveData", null)
                        .WithMany("Players")
                        .HasForeignKey("SaveDataId");
                });

            modelBuilder.Entity("GameEngine.Models.Turn", b =>
                {
                    b.HasOne("GameEngine.Models.SaveData", null)
                        .WithMany("ExecutedTurns")
                        .HasForeignKey("SaveDataId");
                });

            modelBuilder.Entity("GameEngine.Models.SaveData", b =>
                {
                    b.Navigation("ExecutedTurns");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
